### PR TITLE
[optimize]optimize code

### PR DESCRIPTION
**Pull request by qq976739120**
formatted code to comply with the golang specification.
If you don't feel the need, close it.

### CODE REVIEW

**Comment by bjartek** [comment]
Can you change the github file so that it refers to main and not master? So that ci runs? (I have nor fixed this myself yet after branch rename)

**Comment by qq976739120** [comment]
> Can you change the github file so that it refers to main and not master? So that ci runs? (I have nor fixed this myself yet after branch rename)
ok.it works(but why rename to main?)

**Comment by bjartek** [comment]
master/slave is by some deemed to be "wrong" because of the colonial period in history. So main is the new suggested mainline branch on github.

**Comment by bjartek** [comment]
I do not have a computer with me right now so i cannot verify, will do so tonight and merge then. Thanks.

**Comment by bjartek** [comment]
I prefer to squash merge so no need to squash commits

**Comment by bjartek** [comment]
Did you use gofmt to format this automatically?

**Comment by qq976739120** [comment]
> 您是否使用 gofmt 自动格式化？



> Did you use gofmt to format this automatically?

yep,it's easy to use

**Comment by bjartek** [comment]
If you want to you can add gomft github action to the test file?

**Comment by qq976739120** [comment]
> If you want to you can add gomft github action to the test file? Like here [digitalocean/godo#393](https://github.com/digitalocean/godo/issues/393)

maybe in next pr?This may modify many files.

**Comment by bjartek** [comment]
LGTM! Thanks!

**Pull request merged**
